# Generated by Django 3.2.3 on 2021-08-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('postcode', models.CharField(blank=True, max_length=12, verbose_name='Postal code')),
                ('address_line_1', models.CharField(blank=True, max_length=150, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='Address line 2')),
                ('town_city', models.CharField(blank=True, max_length=150, verbose_name='Town/City/State')),
                ('delivery_instructions', models.CharField(blank=True, max_length=255, verbose_name='Delivery instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_default', models.BooleanField(default=False, help_text='Change default address', verbose_name='Default address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser', verbose_name='Custom user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
