# Generated by Django 3.2.3 on 2021-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
