# Generated by Django 3.2.3 on 2021-08-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productspecificationvalue_additional_price'),
        ('cart', '0002_alter_cartitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cart.cartitem')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productspecification')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productspecificationvalue')),
            ],
        ),
    ]
