# Generated by Django 3.2.3 on 2021-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productspecification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationvalue',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'The price must be between 0 and 9999999.99'}}, help_text='Maximum 9999999.99', max_digits=9, verbose_name='Additional price'),
        ),
    ]
