version: "3.9"

services:
  fatbowl:
    build:
      context: ./backend
    container_name: fatbowl
    volumes:
      - ./backend:/usr/src/fatbowl/backend
    ports:
      - 8000:8000
    environment:
      - FROM_DOCKER=1

  fatbowl-frontend:
    build:
        context: ./frontend/core
    container_name: fatbowl-frontend
    volumes:
      - ./frontend/core:/usr/src/fatbowl/frontend
    ports:
      - 3000:3000
    environment:
      - FROM_DOCKER=1
    depends_on:
      - fatbowl

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fatbowl
      - fatbowl-frontend