version: "3.9"

services:
  fatbowl:
    build:
      context: ./backend
    container_name: fatbowl
    volumes:
      - ./backend:/usr/src/fatbowl/backend
    ports:
      - 8000:8000
    environment:
      - FROM_DOCKER=1

  nginx:
    image: nginx:latest
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:8080
      - 443:443
    volumes:
      # - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro\
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - fatbowl
  
  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
