# Generated by Django 3.2.3 on 2021-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Delivery name')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999999.99'}}, help_text='Maximum 9999999.99', max_digits=9, verbose_name='Delivery price')),
                ('method', models.CharField(choices=[('IS', 'In store'), ('HD', 'Home delivery'), ('DD', 'Digital delivery')], help_text='Required', max_length=255, verbose_name='Delivery method')),
                ('timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='Delivery timeframe')),
                ('window', models.CharField(help_text='Required', max_length=255, verbose_name='Delivery window')),
                ('order', models.IntegerField(default=0, help_text='Required', verbose_name='List order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery option',
                'verbose_name_plural': 'Delivery options',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Payment option')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment option',
                'verbose_name_plural': 'Payment options',
            },
        ),
    ]
