# Generated by Django 3.2.3 on 2021-07-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('postcode', models.CharField(blank=True, max_length=12, verbose_name='Postal code')),
                ('address_line_1', models.CharField(blank=True, max_length=150, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='Address line 2')),
                ('town_city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
