# Generated by Django 3.2.3 on 2021-08-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productspecificationvalue_additional_price'),
        ('order', '0002_auto_20210809_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='order.orderitem')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productspecification')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productspecificationvalue')),
            ],
        ),
    ]
